apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-new-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: poxos
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/vol1/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kube-node2
