apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
  labels:
    app: wordpress
spec:
  storageClassName: poxos
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
